# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('0', 'low'), ('1', 'moderate'), ('2', 'high')], default='0', max_length=1),
            preserve_default=False,
        ),
    ]
