# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20160717_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('0', 'low'), ('1', 'moderate'), ('2', 'high')], default='0', max_length=1),
        ),
    ]
